export const todoConstants = {
  ADD_TODO: 'ADD_TODO',
  DELETE_TODO: 'DELETE_TODO',
  GET_TODOS: 'GET_TODOS',
  LOADING: 'LOADING',
  ALERT_SUCCESS: 'ALERT_SUCCESS',
  ALERT_DANGER: 'ALERT_DANGER',
  CHECKED: 'CHECKED',
}